routes/web.php
<?php

use App\Http\Controllers\BitrixWebhookController;
use App\Http\Controllers\Roles\Cachier\ContactController;
use App\Http\Controllers\Roles\Cachier\LeadController;
use Illuminate\Support\Facades\Route;

Auth::routes([
    'confirm' => false, 'forgot' => false, 'login' => true,
    'register' => false, 'reset' => false, 'verification' => false,
]);

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('logs', [\Rap2hpoutre\LaravelLogViewer\LogViewerController::class, 'index']);

# Все вебхуки поступающие от Б24
Route::post('/bitrix/webhooks', [BitrixWebhookController::class, 'emit']);

# Маршруты для установки ролей
Route::group(['middleware' => ['auth', 'auth.bitrix']], function () {
    Route::get('/auth/roles/set', [\App\Http\Controllers\Auth\SetRolesController::class, 'index'])->name('auth.roles.view');
    Route::post('/auth/roles/set', [\App\Http\Controllers\Auth\SetRolesController::class, 'set'])->name('auth.roles.set');
});

Route::group(['middleware' => ['auth', 'auth.bitrix', 'verify_roles']], function () {
    Route::get('/home', [\App\Http\Controllers\RedirectRoleController::class, 'redirectRoleRoute']);

    # Маршруты для пользователя с ролью кассир
    Route::group(['middleware' => ['role:cachier'], 'prefix' => 'cachier'], function () {
        Route::get('/', function () {
            return redirect()->route('leads.create');
        });

        Route::get('/leads/create', [LeadController::class, 'create'])->name('leads.create');
        Route::post('/leads/store', [LeadController::class, 'store'])->name('leads.store');
    });

    # Маршруты для пользователя с ролью флорист
    Route::group(['middleware' => ['role:grower'], 'prefix' => 'grower'], function () {
        Route::get('/', [\App\Http\Controllers\Roles\Grower\HomeController::class, 'index'])
            ->name('growers.index');

        Route::get('/chat', [\App\Http\Controllers\Roles\Grower\ChatController::class, 'index'])
            ->name('growers.chat');

        Route::get('/tasks', [\App\Http\Controllers\Roles\Grower\TaskController::class, 'index'])
            ->name('growers.tasks');

        Route::get('/tasks/{id}/edit', [\App\Http\Controllers\Roles\Grower\TaskController::class, 'edit'])
            ->name('growers.tasks.edit');

        Route::post('/tasks/{id}/start', [\App\Http\Controllers\Roles\Grower\TaskController::class, 'start'])
            ->name('growers.tasks.start');

        Route::post('/tasks/{id}/complete', [\App\Http\Controllers\Roles\Grower\TaskController::class, 'complete'])
            ->name('growers.tasks.complete');

        Route::get('/tasks/{id}/photos/view', [\App\Http\Controllers\Roles\Grower\PhotoController::class, 'view']);
    });

    # Маршруты для пользователя с ролью упаковщик
    Route::group(['middleware' => ['role:packer'], 'prefix' => 'packer'], function () {
        Route::get('/', fn() => redirect('/packer/search'));

        Route::get('/search', [\App\Http\Controllers\Roles\Packer\HomeController::class, 'search'])
            ->name('packer.search-deal');

        Route::get('/deals/{id}/storage', [\App\Http\Controllers\Roles\Packer\HomeController::class, 'storage'])
            ->name('packer.storage-deal');
    });

    # Маршруты для логиста
    Route::group(['middleware' => ['role:logistician'], 'prefix' => 'logistician'], function () {
        Route::get('/', [\App\Http\Controllers\Roles\Logistician\LogisticianHomeController::class, 'home']);
    });

    # Маршруты для администратора
    Route::group(['middleware' => ['role:administrator'], 'prefix' => 'administrator'], function () {
        Route::get('/', static fn() => redirect('/administrator/users'));

        Route::resource('users', \App\Http\Controllers\Roles\Administrator\UserController::class)
            ->only('index', 'edit', 'update');

        Route::get('/users/{user}/create', [\App\Http\Controllers\Roles\Administrator\UserController::class, 'create'])
            ->name('users.create');

        Route::post('/users/{user}/store', [\App\Http\Controllers\Roles\Administrator\UserController::class, 'store'])
            ->name('users.store');
    });
});

Route::get('/test', function () {
    $contact = new \App\Models\Contact();
    dd($contact->bitrix_contact_id);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    protected $fillable = [
        'bitrix_id',
        'name',
        'email',
        'personal_mobile',
        'password',
        'camera_index'
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/Roles/Administrator/UserController.php
<?php

namespace App\Http\Controllers\Roles\Administrator;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use App\Repositories\Database\RoleRepository;
use App\Services\Bitrix24\BatchService;
use App\Services\Bitrix24\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Spatie\FlareClient\Http\Exceptions\NotFound;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class UserController extends Controller
{
    private RoleRepository $roleRepository;

    private UserService $userService;

    private BatchService $batchService;

    public function __construct(RoleRepository $roleRepository,UserService $userService, BatchService $batchService)
    {
        $this->roleRepository = $roleRepository;

        $this->userService = $userService;

        $this->batchService = $batchService;
    }

    public function index()
    {
        try {
            $users = User::with('roles')->get();
            $bitrixUsers = $this->userService->get();

            $commands = $this->commands(ceil($bitrixUsers['total'] / 50));

            $bitrixUsers = $this->batchService->batch($commands);
            $bitrixUsers = collect($bitrixUsers['result'])->flatMap(fn($user) => $user);

            return view('roles.administrator.users.index', compact('users', 'bitrixUsers'));
        } catch (\Exception $exception) {
            dd($exception);
        }
    }

    public function edit(Request $request, int $user)
    {
        $user = User::with('roles')->findOrFail($user);
        $roles = Role::all();

        $externalUser = $user->bitrix_id ?
            $this->userService->get(['id' => $user->bitrix_id]) :
            null;

        if (!$externalUser) {
            throw new NotFound('Пользователя в Битрикс24 отсутствует.');
        }

        return view('roles.administrator.users.edit', compact('user', 'roles'));
    }

    public function update(Request $request, int $user)
    {
        $user = User::with('roles')->findOrFail($user);

        $externalUser = $user->bitrix_id ?
            $this->userService->get(['id' => $user->bitrix_id])['result'] :
            null;

        if (!$externalUser) {
            throw new NotFound('Пользователь в Битрикс24 отсутствует.');
        }

        $externalUser = $externalUser[0];

        $roles = $request->get('roles');

        foreach ($user->roles as $role) {
            $user->removeRole($role);
        }

        foreach ($roles as $role) {
            $user->assignRole($role);
        }

        $isGenerate = (bool)$request->get('generate');
        $password = $isGenerate ? Str::random(10) : null;

        if ($isGenerate) {
            $user->password = Hash::make($password);
            $user->save();
        }

        $request->session()->flash('password', $password);

        return redirect()->route('users.edit', ['user' => $user])->with('success', 'Права успешно изменены.');
    }

    public function create(int $id)
    {
        $roles = $this->roleRepository->all();

        $externalUser = $this->userService->get(['id' => $id])[0];
        if (!$externalUser) {
            throw new NotFoundHttpException('Пользователь в Б24 с ID: ' . $id . 'не найден.');
        }

        return view('roles.administrator.users.create', compact('externalUser', 'roles'));
    }

    public function store(Request $request, int $user)
    {
        $response = $this->userService->get(['ID' => $user]);

        $external = $response ? $response[0] : null;
        if (!$external) {
            throw new \Exception('Пользователь в Б24 отсутствует');
        }

        $internal = User::where('bitrix_id', '=', $external['ID'])->first();
        if ($internal) {
            throw new \Exception('Пользователь уже существует.');
        }

        $roles = $request->get('roles');

        $password = Str::random(10);

        $create = User::create([
            'name' => $external['NAME'],
            'email' => $external['EMAIL'],
            'password' => Hash::make($password),
            'bitrix_id' => $external['ID']
        ]);

        foreach ($roles as $role) {
            $create->assignRole($role);
        }

        return redirect()
            ->route('users.index')
            ->with(
                'admin.user.created',
                'Пользователь успешно создан.' . "\r\n" . 'Логин: ' . $create['email'] . "\r\n" . 'Пароль: ' . $password
            );
    }

    public function commands($pages): array
    {
        $batch = [];

        for ($i = 1; $i <= $pages; $i++) {
            $batch['get_' . $i] = 'user.get?' . http_build_query([
                    'start' => '$next[get_' . ($i - 1) . ']',
                ]);
        }

        return $batch;
    }
}

resources/views/roles/administrator/users/create.blade.php
@extends('layouts.app')

@section('title', 'Создание пользователя')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Создание пользователя и указание прав</h1>

                <form action="{{ route('users.store', ['user' => $externalUser['ID']]) }}" method="post">
                    @csrf

                    @method('POST')

                    <div class="form-group mb-2">
                        <label for="roles">Роли сотрудника</label>
                        <select name="roles[]" multiple id="roles" class="form-control">
                            <option selected disabled>Выберите роли</option>
                            @foreach($roles as $role)
                                <option value="{{ $role->id }}">{{ $role->ru_name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-success">
                            Создать
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/administrator/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Изменение прав пользователя')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                @if(session()->get('success'))
                    <div class="alert alert-success">
                        Права успешно изменены.
                        @if(session()->has('password'))
                            Новый пароль: {{ session()->get('password') }}
                        @endif
                    </div>
                @endif

                <h1>Изменение прав пользователя</h1>

                <form action="{{ route('users.update', ['user' => $user]) }}" method="POST">'
                    @csrf
                    @method('PUT')
                    <div class="form-group mb-2">
                        <label for="email">Адрес электронной почты</label>
                        <input type="email" id="email" class="form-control" value="{{ $user->email }}" disabled>
                    </div>

                    <div class="form-group mb-2">
                        <label for="roles">Роли</label>
                        <select name="roles[]" id="roles" class="form-control" multiple size="5">
                            @foreach($roles as $role)
                                @php
                                    $exist = $user->roles->first(fn ($r) => $r->id === $role->id);
                                @endphp

                                <option value="{{ $role->id }}" @if($exist) selected @endif>
                                    {{ $role->ru_name }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group mb-2">
                        <label for="generate">Сгенерировать новый пароль</label>
                        <input type="checkbox" value="1" id="generate" name="generate">
                    </div>

                    <div class="form-group">
                        <button class="btn btn-success">
                            Обновить
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/administrator/users/index.blade.php
@extends('layouts.app')

@section('title', 'Пользователи')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Сотрудники Б24</h1>

                @if(session()->has('admin.user.created'))
                    <div class="alert alert-success">
                        {{ session()->get('admin.user.created') }}
                    </div>
                @endif

                <div class="table-responsive">
                    <table class="table">

                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Синхронизация</th>
                            <th scope="col">ФИО</th>
                            <th scope="col">Телефон</th>
                            <th scope="col">Почта</th>
                            <th scope="col">Роли</th>
                            <th scope="col">Действия</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($bitrixUsers as $bitrixUser)
                            @php
                                $localUser = $users->first(function ($user) use ($bitrixUser) {
                                    return $user->bitrix_id === $bitrixUser['ID'];
                                });
                            @endphp

                            <tr>
                                <th scope="row">{{ $bitrixUser['ID'] }}</th>
                                <td>{{ $localUser ? 'Синхронизован' : 'Не синхронизован' }}</td>
                                <td>{{ $bitrixUser['NAME'] ?? 'Не задано' }}</td>
                                <td>{{ $bitrixUser['PHONE'] ?? 'Не задано' }}</td>
                                <td>{{ $bitrixUser['EMAIL'] ?? 'Email не указан'  }}</td>
                                <td>
                                    @if($localUser)
                                        @foreach($localUser->roles as $role)
                                            {{ $role->ru_name }},
                                        @endforeach
                                    @endif
                                </td>
                                <td>
                                    @if($localUser)
                                        <a class="btn btn-primary"
                                           href="{{ route('users.edit', ['user' => $localUser]) }}">Обновить права</a>
                                    @else
                                        <a class="btn btn-success"
                                           href="{{ route('users.create', ['user' => $bitrixUser['ID']]) }}">Создать
                                            пользователя</a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection